cpus_per_task: 16
eval_name: video_classification_frozen
folder: /gpfs/milgram/pi/scherzer/yl2428/pd-analysis/outputs/foundation_model_minimal_hand_tasks/vjepa2_evals/item_3_4/fold_0
mem_per_gpu: 220G
nodes: 8
max_workers: 8
resume_checkpoint: true
tag: pd-hand-item-3_4-fold-0
tasks_per_node: 8
experiment:
  classifier:
    num_heads: 16
    num_probe_blocks: 4
    head_type: corn
    selection_metric: quadratic_weighted_kappa
    corn_pos_weight: auto
  data:
    dataset_type: ClipDataset
    dataset_train: /gpfs/milgram/pi/scherzer/yl2428/pd-analysis/outputs/foundation_model_minimal_hand_tasks/splits/item_3_4/fold_0_train.csv
    dataset_val: /gpfs/milgram/pi/scherzer/yl2428/pd-analysis/outputs/foundation_model_minimal_hand_tasks/splits/item_3_4/fold_0_val.csv
    frame_step: 2
    frames_per_clip: 16
    num_classes: 5
    num_segments: 12
    num_views_per_segment: 3
    resolution: 384
  optimization:
    batch_size: 2
    multihead_kwargs:
    - final_lr: 0.0
      final_weight_decay: 0.01
      lr: 0.005
      start_lr: 0.005
      warmup: 0.0
      weight_decay: 0.01
    - final_lr: 0.0
      final_weight_decay: 0.01
      lr: 0.003
      start_lr: 0.003
      warmup: 0.0
      weight_decay: 0.01
    - final_lr: 0.0
      final_weight_decay: 0.01
      lr: 0.001
      start_lr: 0.001
      warmup: 0.0
      weight_decay: 0.01
    - final_lr: 0.0
      final_weight_decay: 0.01
      lr: 0.0003
      start_lr: 0.0003
      warmup: 0.0
      weight_decay: 0.01
    - final_lr: 0.0
      final_weight_decay: 0.01
      lr: 0.0001
      start_lr: 0.0001
      warmup: 0.0
      weight_decay: 0.01
    - final_lr: 0.0
      final_weight_decay: 0.1
      lr: 0.005
      start_lr: 0.005
      warmup: 0.0
      weight_decay: 0.1
    - final_lr: 0.0
      final_weight_decay: 0.1
      lr: 0.003
      start_lr: 0.003
      warmup: 0.0
      weight_decay: 0.1
    - final_lr: 0.0
      final_weight_decay: 0.1
      lr: 0.001
      start_lr: 0.001
      warmup: 0.0
      weight_decay: 0.1
    - final_lr: 0.0
      final_weight_decay: 0.1
      lr: 0.0003
      start_lr: 0.0003
      warmup: 0.0
      weight_decay: 0.1
    - final_lr: 0.0
      final_weight_decay: 0.1
      lr: 0.0001
      start_lr: 0.0001
      warmup: 0.0
      weight_decay: 0.1
    - final_lr: 0.0
      final_weight_decay: 0.4
      lr: 0.005
      start_lr: 0.005
      warmup: 0.0
      weight_decay: 0.4
    - final_lr: 0.0
      final_weight_decay: 0.4
      lr: 0.003
      start_lr: 0.003
      warmup: 0.0
      weight_decay: 0.4
    - final_lr: 0.0
      final_weight_decay: 0.4
      lr: 0.001
      start_lr: 0.001
      warmup: 0.0
      weight_decay: 0.4
    - final_lr: 0.0
      final_weight_decay: 0.4
      lr: 0.0003
      start_lr: 0.0003
      warmup: 0.0
      weight_decay: 0.4
    - final_lr: 0.0
      final_weight_decay: 0.4
      lr: 0.0001
      start_lr: 0.0001
      warmup: 0.0
      weight_decay: 0.4
    - final_lr: 0.0
      final_weight_decay: 0.8
      lr: 0.005
      start_lr: 0.005
      warmup: 0.0
      weight_decay: 0.8
    - final_lr: 0.0
      final_weight_decay: 0.8
      lr: 0.003
      start_lr: 0.003
      warmup: 0.0
      weight_decay: 0.8
    - final_lr: 0.0
      final_weight_decay: 0.8
      lr: 0.001
      start_lr: 0.001
      warmup: 0.0
      weight_decay: 0.8
    - final_lr: 0.0
      final_weight_decay: 0.8
      lr: 0.0003
      start_lr: 0.0003
      warmup: 0.0
      weight_decay: 0.8
    - final_lr: 0.0
      final_weight_decay: 0.8
      lr: 0.0001
      start_lr: 0.0001
      warmup: 0.0
      weight_decay: 0.8
    num_epochs: 20
    use_bfloat16: true
    use_pos_embed: false
model_kwargs:
  checkpoint: /gpfs/milgram/pi/scherzer/yl2428/vjepa2/checkpoints/vjepa2_1_vitl_dist_vitG_384.pt
  module_name: evals.video_classification_frozen.modelcustom.vit_encoder_multiclip
  pretrain_kwargs:
    encoder:
      checkpoint_key: ema_encoder
      img_temporal_dim_size: 1
      model_name: vit_large
      patch_size: 16
      tubelet_size: 2
      uniform_power: true
      use_rope: true
  wrapper_kwargs:
    max_frames: 128
    use_pos_embed: false
num_workers: 8
wandb:
  enabled: true
  project: pd-hand-vjepa2
  entity: yl2428
  mode: online
  group: pd-hand-item-3_4
  name: pd-hand-item-3_4-fold-0
  id: pd-hand-item-3_4-fold-0
  resume: allow
  job_type: video_classification_frozen
  tags:
  - vjepa2.1
  - minimal-hand-tasks
  - corn
  - item-3_4
