cpus_per_task: 2
eval_name: video_classification_frozen
folder: /gpfs/milgram/pi/scherzer/yl2428/pd-analysis/outputs/foundation_model_minimal_hand_tasks/vjepa2_adaptive/item_3_4/fold_0_tokenstats_frozen_statsmlp
mem_per_gpu: 80G
nodes: 1
max_workers: 2
resume_checkpoint: false
tag: pd-hand-item-3_4-fold-0-adaptive-tokenstats-frozen-statsmlp
tasks_per_node: 1
experiment:
  classifier:
    num_heads: 4
    num_probe_blocks: 1
    head_type: adaptive_stats_corn
    selection_metric: quadratic_weighted_kappa
    corn_pos_weight: auto
    head_kwargs:
      hidden_dim: 512
      dropout: 0.35
      percentiles:
      - 0.1
      - 0.25
      - 0.5
      - 0.75
      - 0.9
  data:
    dataset_type: ClipDataset
    dataset_train: /gpfs/milgram/pi/scherzer/yl2428/pd-analysis/outputs/foundation_model_minimal_hand_tasks/splits/item_3_4/fold_0_train.csv
    dataset_val: /gpfs/milgram/pi/scherzer/yl2428/pd-analysis/outputs/foundation_model_minimal_hand_tasks/splits/item_3_4/fold_0_val.csv
    frame_step: 1
    frames_per_clip: 32
    num_classes: 5
    num_segments: 1
    num_views_per_segment: 1
    resolution: 384
    dataset_kwargs:
      hand_crop: true
      crop_size: 128
      crop_scale: 1.5
      adaptive_num_clips: true
      adaptive_duration_col: duration_s
      adaptive_min_clips: 1
  optimization:
    batch_size: 1
    multihead_kwargs:
    - lr: 0.0003
      start_lr: 0.0003
      final_lr: 0.0
      weight_decay: 0.05
      final_weight_decay: 0.05
      warmup: 0.0
    num_epochs: 40
    use_bfloat16: true
    use_pos_embed: false
    finetune_encoder: false
model_kwargs:
  checkpoint: /gpfs/milgram/pi/scherzer/yl2428/vjepa2/checkpoints/vjepa2_1_vitl_dist_vitG_384.pt
  module_name: evals.video_classification_frozen.modelcustom.vit_encoder_multiclip_vjepa21
  pretrain_kwargs:
    encoder:
      checkpoint_key: ema_encoder
      model_name: vit_large
      patch_size: 16
      tubelet_size: 2
      uniform_power: false
      use_rope: true
      img_temporal_dim_size: 1
      interpolate_rope: true
      modality_embedding: true
      n_output_distillation: 1
      strict_state_dict: true
      use_activation_checkpointing: true
  wrapper_kwargs:
    max_frames: 4096
    use_pos_embed: true
    clip_batch_size: 4
    pool_tokens: mean_std_max
    return_segment_outputs: true
num_workers: 4
wandb:
  enabled: true
  project: pd-hand-vjepa2
  entity: yl2428
  mode: online
  group: pd-hand-item-3_4-adaptive
  name: pd-hand-item-3_4-fold-0-adaptive-tokenstats-frozen-statsmlp
  id: pd-hand-item-3_4-fold-0-adaptive-tokenstats-frozen-statsmlp
  resume: allow
  job_type: video_classification_frozen
  tags:
  - vjepa2.1
  - adaptive-windows
  - tokenstats
  - frozen
  - statsmlp
  - corn
  - item-3_4
